codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto
        if_ci_failed: error

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
