[.]
checkstyle = 0
pmd = 0
spotbugs = 0

[audio-core]
checkstyle = 0
pmd = 23
spotbugs = 2

[audio-plugin-api]
checkstyle = 0
pmd = 2
spotbugs = 0

[audio-geometry]
checkstyle = 13
pmd = 9
spotbugs = 0

[audio-dsp]
checkstyle = 20
pmd = 100
spotbugs = 10

[audio-app]
checkstyle = 6
pmd = 62
spotbugs = 19

[audio-acquisition]
checkstyle = 5
pmd = 4
spotbugs = 0

[audio-experimental-acoustic]
checkstyle = 91
pmd = 64
spotbugs = 3
